Pipeline M21 14 - pipeline table
digital-futures-academy/crm-frontend pull request #6
Opened 2021-05-24 10:51 UTC by paulinakoz

2021-05-24 12:03 UTC, dearshrewdwit commented
@paulinakoz Currently it's failing CI
- let's try a blunt tool: can you refresh your dependencies by removing the `package.lock` file and installing again by `npm install`

2021-05-24 15:44 UTC, dearshrewdwit requested changes
Great job passing CI!

The only things stopping this PR are
1.  the `.idea` directory - please add a commit removing the directory from version control
2. squash your commits!

2021-05-24 16:06 UTC, dearshrewdwit commented on cypress.json
> +  "reporter": "cypress-mochawesome-reporter"
what's this for?

2021-05-24 16:08 UTC, sawaveys commented on cypress.json
> +  "reporter": "cypress-mochawesome-reporter"
We added cypress mochawesome because the jenkins test said it was missing

2021-05-24 16:32 UTC, dearshrewdwit commented on cypress.json
> +  "reporter": "cypress-mochawesome-reporter"
Can you document that as part of the PR description?

2021-05-24 19:13 UTC, dearshrewdwit approved these changes
Nice. Let's get it in!

2021-05-25 13:40 UTC, mattfann approved these changes
All looks good - well done on getting through to a PR!

2021-05-25 13:42 UTC, merged